### ISSUE TITLE
Quesetion about sync with latest paper

### ISSUE THREAD

**Issue by chenshihfang** [Little-Podi/Transformer_Tracking#3]
Hi, thank you for your update,
I'm curious, do you manually search ArXiv to stay updated on the latest paper publications, 
or are there automated methods available?

**Comment by Little-Podi** [comment]
Nice question. I keep tracing the arXiv papers that are submitted to [cs.CV](https://arxiv.org/list/cs.CV/recent) category from time to time. I am also using [scholar inbox](https://www.scholar-inbox.com), which recommends the newly published papers that match your area of interests. It can learn your tastes via an iterative training mechanism.

**Comment by chenshihfang** [comment]
> Nice question. I keep tracing the arXiv papers that are submitted to [cs.CV](https://arxiv.org/list/cs.CV/recent) category from time to time. I am also using [scholar inbox](https://www.scholar-inbox.com), which recommends the newly published papers that match your area of interests. It can learn your tastes via an iterative training mechanism.

Cool, thanks
